// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Species } from "./Species";

export interface Ability { ability: Species, is_hidden: boolean, slot: bigint, }