// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Crystal { back_default: string, back_shiny: string, back_shiny_transparent: string, back_transparent: string, front_default: string, front_shiny: string, front_shiny_transparent: string, front_transparent: string, }