// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DreamWorld } from "./DreamWorld";
import type { Home } from "./Home";

export interface GenerationVii { icons: DreamWorld, "ultra-sun-ultra-moon": Home, }