// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Sprites } from "./Sprites";

export interface GenerationV { "black-white": Sprites, }