// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gold } from "./Gold";
import type { OfficialArtwork } from "./OfficialArtwork";

export interface GenerationIii { emerald: OfficialArtwork, "firered-leafgreen": Gold, "ruby-sapphire": Gold, }