// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Crystal } from "./Crystal";
import type { Gold } from "./Gold";

export interface GenerationIi { crystal: Crystal, gold: Gold, silver: Gold, }