// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Gold { back_default: string, back_shiny: string, front_default: string, front_shiny: string, front_transparent: string | null, }