// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Species } from "./Species";
import type { VersionDetail } from "./VersionDetail";

export interface HeldItem { item: Species, version_details: Array<VersionDetail>, }