// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Home { front_default: string, front_female: string, front_shiny: string, front_shiny_female: string, }