// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Ability } from "./Ability";
import type { GameIndex } from "./GameIndex";
import type { HeldItem } from "./HeldItem";
import type { Move } from "./Move";
import type { Species } from "./Species";
import type { Sprites } from "./Sprites";
import type { Stat } from "./Stat";
import type { Type } from "./Type";

export interface Manga { abilities: Array<Ability>, base_experience: bigint, forms: Array<Species>, game_indices: Array<GameIndex>, height: bigint, held_items: Array<HeldItem>, id: bigint, is_default: boolean, location_area_encounters: string, moves: Array<Move>, name: string, order: bigint, past_types: string[], species: Species, sprites: Sprites, stats: Array<Stat>, types: Array<Type>, weight: bigint, }