// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Species } from "./Species";
import type { VersionGroupDetail } from "./VersionGroupDetail";

export interface Move { move: Species, version_group_details: Array<VersionGroupDetail>, }