// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DreamWorld } from "./DreamWorld";
import type { Home } from "./Home";
import type { OfficialArtwork } from "./OfficialArtwork";

export interface Other { dream_world: DreamWorld, home: Home, "official-artwork": OfficialArtwork, }