// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface RedBlue { back_default: string, back_gray: string, back_transparent: string, front_default: string, front_gray: string, front_transparent: string, }