// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Other } from "./Other";
import type { Versions } from "./Versions";

export interface Sprites { back_default: string, back_female: string, back_shiny: string, back_shiny_female: string, front_default: string, front_female: string, front_shiny: string, front_shiny_female: string, other: Other | null, versions: Versions | null, animated: Sprites | null, }