// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Species } from "./Species";

export interface VersionGroupDetail { level_learned_at: bigint, move_learn_method: Species, version_group: Species, }