// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GenerationI } from "./GenerationI";
import type { GenerationIi } from "./GenerationIi";
import type { GenerationIii } from "./GenerationIii";
import type { GenerationIv } from "./GenerationIv";
import type { GenerationV } from "./GenerationV";
import type { GenerationVii } from "./GenerationVii";
import type { GenerationViii } from "./GenerationViii";
import type { Home } from "./Home";

export interface Versions { "generation-i": GenerationI, "generation-ii": GenerationIi, "generation-iii": GenerationIii, "generation-iv": GenerationIv, "generation-v": GenerationV, "generation-vi": Record<string, Home>, "generation-vii": GenerationVii, "generation-viii": GenerationViii, }